apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: unifi-cert
  namespace: unifi
  labels:
    app.kubernetes.io/instance: unifi
spec:
  secretName: unifi-cert
  dnsNames:
    - unifi.garrettholland.com
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
