apiVersion: longhorn.io/v1beta1
kind: Volume
metadata:
  labels:
    longhornvolume: unifi
    app.kubernetes.io/instance: unifi
  name: unifi
  namespace: longhorn-system
spec:
  replicaAutoBalance: disabled
  dataLocality: disabled
  accessMode: rwo
  engineImage: longhornio/longhorn-engine:v1.2.3
  frontend: blockdev
  numberOfReplicas: 2
  size: "1073741824"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: unifi-pvc
  namespace: unifi
  labels:
    app.kubernetes.io/instance: unifi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: unifi-pv
  storageClassName: longhorn-static
  volumeMode: Filesystem
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: unifi-pv
  labels:
    app.kubernetes.io/instance: unifi
spec:
  capacity:
    storage: 1Gi
  csi:
    driver: driver.longhorn.io
    volumeHandle: unifi
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: "2"
  accessModes:
    - ReadWriteOnce
  claimRef:
    kind: PersistentVolumeClaim
    name: unifi-pvc
    namespace: unifi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-static
  volumeMode: Filesystem
