apiVersion: config.openshift.io/v1
kind: ClusterVersion
metadata:
  name: version
  labels:
    app.kubernetes.io/instance: okd-configuration
spec:
  channel: stable-4.22
  clusterID: a5b616a6-0ba8-4548-b6eb-77cc5decf47a
  desiredUpdate:
    force: true
    image: quay.io/okd/scos-release@sha256:371309d97da5c7f595662cb7d2a9bf11c05fe96f2bf54898e6da60f13c12ffda
    version: 4.22.0-okd-scos.0
  upstream: https://amd64.origin.releases.ci.openshift.org/graph
