apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lab-ingress-cert
  namespace: openshift-ingress
spec:
  dnsNames:
    - "*.lab.garrettholland.com"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: lab-ingress-cert-tls
