apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: influxdb
  namespace: influxdb
spec:
  entryPoints:
    - web
    - websecure
  tls:
    domains:
      - main: influxdb.garrettholland.com
  routes:
    - kind: Rule
      match: Host(`influxdb.garrettholland.com`)
      services:
        - kind: Service
          name: influxdb
          port: 8086
