apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - volume.yaml
  - configmap.yaml
  - ingressroute.yaml
  - service.yaml
  - secret.yaml
  - deployment.yaml
