apiVersion: longhorn.io/v1beta1
kind: Volume
metadata:
  labels:
    longhornvolume: influxdb
    app.kubernetes.io/instance: influxdb
  name: influxdb
  namespace: longhorn-system
spec:
  replicaAutoBalance: disabled
  dataLocality: disabled
  accessMode: rwo
  engineImage: longhornio/longhorn-engine:v1.2.3
  frontend: blockdev
  numberOfReplicas: 2
  size: "5368709120"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: influxdb-pvc
  namespace: influxdb
  labels:
    app.kubernetes.io/instance: influxdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: influxdb-pv
  storageClassName: longhorn-static
  volumeMode: Filesystem
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: influxdb-pv
  labels:
    app.kubernetes.io/instance: influxdb
spec:
  capacity:
    storage: 5Gi
  csi:
    driver: driver.longhorn.io
    volumeHandle: influxdb
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: "2"
  accessModes:
    - ReadWriteOnce
  claimRef:
    kind: PersistentVolumeClaim
    name: influxdb-pvc
    namespace: influxdb
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-static
  volumeMode: Filesystem
