apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
resources:
  - ./namespace.yaml
  - ./traefik-crd-rbac.yaml
  - ./clusterrole.yaml
  - ./dashboard-hook-ingressroute.yaml
  - ./deployment.yaml
  - ./serviceaccount.yaml
  - ./service.yaml
  - ./traefik-ui.yaml
