apiVersion: v1
kind: Secret
metadata:
  name: github-pac-provider
  namespace: tekton-ci
type: Opaque
stringData:
  token: <path:projects/812524172865/secrets/github-pac-token#github-pac-token>
  webhook.secret: <path:projects/812524172865/secrets/github-pac-webhook-secret#github-pac-webhook-secret>
