apiVersion: v1
kind: Secret
metadata:
  name: pipelines-as-code-secret
  namespace: openshift-pipelines
type: Opaque
stringData:
  github-application-id: <path:projects/812524172865/secrets/github-pac-app-id#github-pac-app-id>
  github-private-key: <path:projects/812524172865/secrets/github-pac-app-private-key#github-pac-app-private-key>
  webhook.secret: <path:projects/812524172865/secrets/github-pac-app-webhook-secret#github-pac-app-webhook-secret>
