apiVersion: v1
kind: Secret
metadata:
  name: harbor-push-secret
  namespace: tekton-ci
  annotations:
    tekton.dev/docker-0: https://harbor.lab.garrettholland.com
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {"auths":{"harbor.lab.garrettholland.com":{"username":"<path:projects/812524172865/secrets/harbor-ci-robot-username#harbor-ci-robot-username>","password":"<path:projects/812524172865/secrets/harbor-ci-robot-password#harbor-ci-robot-password>"}}}
