apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - build-test-serviceaccount.yaml
  - buildah-privileged-rolebinding.yaml
  - github-app-secret.yaml
  - harbor-push-secret.yaml
  - repository.yaml
