apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: remove-fixed-uid-patch.yaml
    target:
      kind: Deployment
      name: cnpg-controller-manager
