apiVersion: v1
kind: ServiceAccount
metadata:
  name: victoriametrics
  namespace: victoriametrics
  labels:
    app.kubernetes.io/name: victoriametrics
    app.kubernetes.io/part-of: victoriametrics
