apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../app
  - ../../drivers
  - scc.yaml

patches:
  - path: secret-patch.yaml
    target:
      kind: Secret
      name: democratic-csi-driver-config
  - patch: |
      - op: add
        path: /spec/template/spec/tolerations
        value:
          - key: nvidia.com/gpu
            operator: Exists
            effect: NoSchedule
    target:
      kind: DaemonSet
      name: democratic-csi-node

images:
  - name: docker.io/democraticcsi/democratic-csi
    newName: harbor.lab.garrettholland.com/lab/democratic-csi
    newTag: latest
