apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-pvc
  namespace: homeassistant
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: truenas-nfs-retain
  resources:
    requests:
      storage: 10Gi
