apiVersion: v1
kind: ServiceAccount
metadata:
  name: media-apps
  namespace: media
  labels:
    app.kubernetes.io/part-of: media-stack
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: system:openshift:scc:anyuid
  namespace: media
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
  - kind: ServiceAccount
    name: media-apps
    namespace: media
