apiVersion: v1
kind: Secret
metadata:
  name: recyclarr-api-keys
  namespace: media
  labels:
    app.kubernetes.io/name: recyclarr
    app.kubernetes.io/part-of: media-stack
type: Opaque
stringData:
  RADARR_API_KEY: <path:projects/812524172865/secrets/radarr-api-key#radarr-api-key>
  SONARR_API_KEY: <path:projects/812524172865/secrets/sonarr-api-key#sonarr-api-key>
