apiVersion: v1
kind: LimitRange
metadata:
  name: zitadel-limits
  namespace: zitadel
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 100m
        memory: 128Mi
      default:
        cpu: 500m
        memory: 512Mi
