apiVersion: v1
kind: Secret
metadata:
  name: zitadel-db-app
  namespace: zitadel
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: zitadel
  password: <path:projects/812524172865/secrets/zitadel-db-password#zitadel-db-password>
---
apiVersion: v1
kind: Secret
metadata:
  name: zitadel-db-superuser
  namespace: zitadel
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: postgres
  password: <path:projects/812524172865/secrets/zitadel-db-superuser-password#zitadel-db-superuser-password>
