apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: zitadel-masterkey
  namespace: zitadel
stringData:
  masterkey: <path:projects/812524172865/secrets/zitadel-masterkey#zitadel-masterkey>
---
# Source: zitadel/templates/secret_zitadel-secrets.yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: zitadel-secrets-yaml
  namespace: zitadel
stringData:
  zitadel-secrets-yaml: |-
    Database:
      postgres:
        User:
          Username: zitadel
          Password: <path:projects/812524172865/secrets/zitadel-db-password#zitadel-db-password>
        Admin:
          Username: postgres
          Password: <path:projects/812524172865/secrets/zitadel-db-superuser-password#zitadel-db-superuser-password>
