apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: zitadeldb
  namespace: zitadel
spec:
  instances: 1
  enableSuperuserAccess: true
  superuserSecret:
    name: zitadel-db-superuser
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: "2"
      memory: 2Gi
  bootstrap:
    initdb:
      database: zitadel
      owner: zitadel
      secret:
        name: zitadel-db-app
  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
      storageClassName: truenas-nfs-retain
