apiVersion: v1
kind: Secret
metadata:
  name: operator-oauth
  namespace: tailscale
stringData:
  client_id: <path:projects/812524172865/secrets/tailscale-oauth-client-id#tailscale-oauth-client-id>
  client_secret: <path:projects/812524172865/secrets/tailscale-oauth-client-secret#tailscale-oauth-client-secret>
