apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: tailscale-subnet-router
allowHostNetwork: false
allowHostPorts: false
allowPrivilegeEscalation: false
allowPrivilegedContainer: false
allowedCapabilities:
  - NET_ADMIN
  - NET_RAW
allowedUnsafeSysctls:
  - net.ipv4.ip_forward
  - net.ipv6.conf.all.forwarding
defaultAddCapabilities: []
fsGroup:
  type: RunAsAny
readOnlyRootFilesystem: false
runAsUser:
  type: MustRunAsRange
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
users:
  - system:serviceaccount:tailscale:proxies
groups: []
volumes:
  - configMap
  - secret
  - emptyDir
  - projected
