apiVersion: v1
baseDomain: garrettholland.com
compute:
- hyperthreading: Enabled   
  name: worker
  replicas: 1
controlPlane:
  hyperthreading: Enabled   
  name: master
  replicas: 1
metadata:
  name: okd
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 192.168.122.0/24
  networkType: OpenShiftSDN # OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  none: {}
fips: false
pullSecret: '{ "auths": { "fake": { "auth": "aWQ6cGFzcwo=" } } }'
sshKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDd1CXzwIpft5wVA/WJqvEk6DH4UmiLmmroZ0IXUcWYmXNWlnvhJx4eFrviz6GyUyDt9hdG69lBScIag5D6UD3ivVFYmBSXkwIludDgA6FeYQfVvpBCR25XgiabpWHhXItbXIYiigzeSF+lmJw6KF+0gTPPKVFtpg8h/eM8j26+lNbGiebYWNbZ0iBRNDZNmrxQAIsgWAszPvZSyZrkFvsLT8U258WsfZbW6q+WelGHQEL4dV2YkfMTZ/jJhq+cOv4Zr7tcbUSw3m90BJ45PhTYEozN0S1GAzyaDchcFabl/RRLa90x+vjJIrp8P/cZVlBunVNtL0HM121QqGiBj8nn garrett@RyzenDesk'