apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lab-ingress-cert
  namespace: openshift-ingress
spec:
  secretName: lab-ingress-cert-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - "*.lab.garrettholland.com"
