- hosts: rocky
  gather_facts: no
  user: garrett
  tasks:

    - name: Upgrade packages
      become: true
      dnf:
        name: '*'
        state: latest
        update_cache: yes
        update_only: no
      register: reg_upgrade_ok
      when: ev_security_only == "no" and reg_dnf_output_all is defined

    - name: install zsh stuff
      become: true
      dnf:
        state: latest
        name:
          - epel-release
          - zsh
          - git
    
    - name: install packages
      become: true
      dnf:
        state: latest
        name:
          - htop
          - sysstat
          - git
          - speedtest-cli
          - wget
          - ca-certificates
          - curl
          - gnupg2
          - pv
          - jq
          - rsync

    - name: install kvm packages
      become: true
      dnf:
        state: latest
        name:
          - cockpit-machines
          - qemu-kvm
          - libvirt-clients
          - libvirt-daemon-system
          - bridge-utils
          - virtinst
          - libvirt-daemon

    - name: change user shell to zsh
      become: true
      user:
        name: "garrett"
        shell: /bin/zsh

    - name: Check if .zshrc exists
      stat:
        path: /home/garrett/.zshrc
      register: zshrc

    - name: Check if .oh-my-zsh exists
      stat:
        path: /home/garrett/.oh-my-zsh
      register: oh_my_zsh

    - name: Cloning  oh-my-zsh
      git:
        repo: https://github.com/ohmyzsh/ohmyzsh.git
        dest: /home/garrett/.oh-my-zsh
      when: not oh_my_zsh.stat.exists
