apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-certificate
  namespace: openshift-ingress-operator
  labels:
    app.kubernetes.io/instance: okd-configuration
spec:
  dnsNames:
    - "*.apps.okd.garrettholland.com"
    - "*.garrettholland.com"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: ingress-certificate
