apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./api-certificate.yaml
  - ./api-server.yaml
  - ./ingress-certificate.yaml
  - ./installplan-approver-cr.yaml
  - ./installplan-approver-crb.yaml
  - ./installplan-approver-sa.yaml
  - ./oauth.yaml
