apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: otel-collector
data:
  otelcol.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      batch:
        timeout: 10s

    exporters:
      debug:
        verbosity: basic
      influxdb:
        endpoint: http://influxdb.influxdb.svc.cluster.local:8181
        token: ${env:INFLUXDB_TOKEN}
        bucket: telegraf

    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [debug, influxdb]
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [debug]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [debug]
