apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: otel-collector
spec:
  template:
    spec:
      containers:
        - name: otel-collector
          env:
            - name: INFLUXDB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: influxdb-token
                  key: token
