apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ./scc.yaml
  - ./secret-influxdb.yaml

patches:
  - path: configmap-patch.yaml
  - path: deployment-patch.yaml
