apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: otel-collector
allowPrivilegeEscalation: false
allowPrivilegedContainer: false
allowedCapabilities: []
defaultAddCapabilities: []
fsGroup:
  type: MustRunAs
  ranges:
    - min: 1000
      max: 65534
readOnlyRootFilesystem: false
runAsUser:
  type: MustRunAsRange
  uidRangeMin: 1000
  uidRangeMax: 65534
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: MustRunAs
  ranges:
    - min: 1000
      max: 65534
users:
  - system:serviceaccount:otel-collector:otel-collector
groups: []
volumes:
  - configMap
  - secret
  - emptyDir
  - projected
