apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - deployment.yaml
  - ingressroute.yaml
  - kustomization.yaml
  - routersnmp-config-cm.yaml
  - secrets.yaml
  - service.yaml
