apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-cert
  namespace: grafana
  labels:
    app.kubernetes.io/instance: grafana
spec:
  secretName: grafana-cert
  dnsNames:
    - grafana.garrettholland.com
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
