apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: grafana
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: InfluxDB
        type: influxdb
        access: proxy
        url: http://influxdb.influxdb.svc.cluster.local:8181
        jsonData:
          version: SQL
          database: telegraf
        secureJsonData:
          token: apiv3_change_me_to_a_random_token
        isDefault: true
