apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ingressroute.yaml
  - service.yaml
  - deployment.yaml
  - volume.yaml
  - certificate.yaml
  # - cm-config.yaml
  # - cm-dashboards.yaml
  # - cm-datasources.yaml
