apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - certificate.yaml
  - ingressroute.yaml
  - service.yaml
  - deployment.yaml
  - volume.yaml
  - cm-datasources.yaml
  - cm-dashboard-provisioning.yaml
  - cm-dashboard-router.yaml
  - cm-dashboard-unifi-aps.yaml
