apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: grafana
  labels:
    app.kubernetes.io/instance: grafana
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: truenas-nfs-retain
  resources:
    requests:
      storage: 5Gi
