apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: default
  namespace: openshift-ingress-operator
spec:
  clientTLS:
    clientCA:
      name: ""
    clientCertificatePolicy: ""
  closedClientConnectionPolicy: Continue
  defaultCertificate:
    name: okd-ingress-cert-tls
  httpCompression: {}
  httpEmptyRequestsPolicy: Respond
  httpErrorCodePages:
    name: ""
  idleConnectionTerminationPolicy: Immediate
  replicas: 2
  routeAdmission:
    wildcardPolicy: WildcardsAllowed
  tuningOptions:
    reloadInterval: 0s
  unsupportedConfigOverrides: null
