apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - secret-mariadb.yaml
  - secret-panel.yaml
  - pvc.yaml
  - service.yaml
  - deployment-panel.yaml
  - deployment-redis.yaml
  - statefulset-mariadb.yaml
  - ingress.yaml
  - certificate.yaml
