apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pterodactyl-mariadb-data
  namespace: pterodactyl
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pterodactyl-mariadb
    app.kubernetes.io/part-of: pterodactyl
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: truenas-nfs-retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pterodactyl-panel-data
  namespace: pterodactyl
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pterodactyl-panel
    app.kubernetes.io/part-of: pterodactyl
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: truenas-nfs-retain
