apiVersion: v1
kind: ServiceAccount
metadata:
  name: pterodactyl-apps
  namespace: pterodactyl
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pterodactyl-apps
    app.kubernetes.io/part-of: pterodactyl
