apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-tunnel-token
  namespace: tekton-ci
type: Opaque
stringData:
  token: <path:projects/812524172865/secrets/cloudflared-pac-tunnel-token#cloudflared-pac-tunnel-token>
